import type { PrecallModuleId } from "../trigger/precall-schedule.js";

export type PrecallCopyModule = {
  id: PrecallModuleId;
  subject: string;
  preview: string;
  body: string;
  role: "confirmation" | "middle" | "final";
  priority?: number;
  bitIndex?: number;
};

export const precallCopy = [
  { id: "confirmation", role: "confirmation", subject: "You're booked. Here's what happens next", preview: "Your call is set for {{meeting_local_date}} at {{meeting_local_time}}.", body: "Hi {{first_name}}, it's {{sender_name}}.\n\nWe're speaking on {{meeting_local_date}} at {{meeting_local_time}} {{attendee_timezone}}.\n\nYou just found us from one of our ads on Facebook or Instagram. Between now and our call, I'll send a short series covering the questions I hear most from people who book after seeing one of those ads. Each email takes less than two minutes to read.\n\nOn the call, we'll look at:\n\n- how your business currently appears across Google and AI search;\n- where visibility or trust signals may be breaking down;\n- whether 45 additional calls in 90 days is realistic from your current baseline;\n- what we would prioritize first if there's a fit.\n\nYou'll leave with a clearer picture of the opportunity even if we decide not to work together.\n\nReply with the biggest question you want answered on the call. I'll make sure we cover it.\n\nLooking forward to speaking on {{meeting_local_weekday}}.\n\nTalk soon,\n\nSanti" },
  { id: "what-we-will-inspect", role: "middle", subject: "Is this just another SEO audit?", preview: "Here's what I'll actually inspect before we speak.", body: "Hi {{first_name}}, it's {{sender_name}}.\n\nA question I hear a lot is, \"Is this just another SEO audit that checks a few rankings?\"\n\nIt isn't.\n\nBefore we speak, I'll look at your Google Business Profile, the outside sources that confirm your business information, what your reviews say about your services, and whether your website gives Google and AI enough evidence to recommend you.\n\nA business can look fine in one place and still go missing when someone asks Google or ChatGPT who to trust.\n\nWe'll use your highest-priority service and market as the lens for the audit.\n\nIf anything about what I'll inspect is unclear, hit reply and ask. We'll go through the findings on the call.\n\nTalk soon,\n\nSanti", priority: 1, bitIndex: 0 },
  { id: "proof-twin-oaks", role: "middle", subject: "Twin Oaks went from 10 monthly calls to 48", preview: "The 380% increase started with an honest baseline.", body: "Hi {{first_name}}, it's {{sender_name}}.\n\nA concern I hear is, \"How do I know you aren't taking credit for calls I was already getting?\"\n\nFair question.\n\nTwin Oaks Dental & Wellness was receiving about 10 monthly calls before the work began. That number later reached 48, a 380% increase.\n\nWe could measure the change because we knew what a normal month looked like before touching anything. Without that baseline, a report can be full of rankings and traffic while never answering whether more people called.\n\nWe'll establish the same starting point for your business before discussing targets. A rough estimate of your normal monthly calls is enough for the conversation.\n\nIf you have questions about how the baseline works, reply and ask. I'll clear them up before the call.\n\nTalk soon,\n\nSanti", priority: 2, bitIndex: 1 },
  { id: "measurement-and-attribution", role: "middle", subject: "What actually counts as a result?", preview: "Calls come first. Rankings and traffic help explain why.", body: "Hi {{first_name}}, it's {{sender_name}}.\n\nA question I hear is, \"What exactly are you measuring?\"\n\nFor us, the main result is additional inbound calls above the baseline we agree on together.\n\nRankings, reviews, citations, profile activity, and AI visibility can help explain why the number changed. They aren't the final result.\n\nOn the call, we'll start with your current monthly call volume. From there, we can discuss how many of those calls are real opportunities and how many become customers, patients, cases, or projects.\n\nThat keeps us from claiming credit for everything and helps us see whether the real constraint is visibility or what happens after someone calls.\n\nHave your best estimate of your current monthly inbound calls handy. It doesn't need to be perfect.\n\nIf you're unsure what should count as an inbound call, reply with the question and I'll clarify it.\n\nTalk soon,\n\nSanti", priority: 3, bitIndex: 2 },
  { id: "already-have-seo", role: "middle", subject: "Already paying for SEO? Good.", preview: "I want to see what's already working before suggesting a change.", body: "Hi {{first_name}}, it's {{sender_name}}.\n\nA concern I hear is, \"We already have an SEO agency. Would this replace them?\"\n\nNot necessarily.\n\nYour current provider may already be doing useful work that should stay in place. I want to see whether they're focused mainly on rankings and website traffic or whether they also manage the profiles, reviews, citations, and outside business information that Google and AI tools use when recommending local companies.\n\nThe easiest way to tell is to look at what they report each month.\n\nIf it's easy, have their latest report handy for the call. I'll account for what they're already doing rather than assuming it should be replaced.\n\nIf you're unsure how we'd work alongside your current provider, reply and ask me directly.\n\nTalk soon,\n\nSanti", priority: 4, bitIndex: 3 },
  { id: "guarantee", role: "middle", subject: "What if the 45 calls don't happen?", preview: "Here's how the guarantee actually works.", body: "Hi {{first_name}}, it's {{sender_name}}.\n\nOne skeptical question I hear is, \"What happens if you don't produce the 45 additional calls?\"\n\nHere's the plain version.\n\nDuring onboarding, we agree on your current call baseline and how additional calls will be measured.\n\nIf the agreed 45-call result isn't reached within 90 days, we continue working without a management fee until it is reached, under the terms of the guarantee.\n\nWe don't count every phone ring and call it ours. The starting point and reporting rules are agreed before the work begins.\n\nIf any part of the guarantee doesn't sit right with you, reply with the question. I'd rather answer it directly than leave room for surprises later.\n\nWe'll go through the details when we speak on {{meeting_local_weekday}}.\n\nTalk soon,\n\nSanti", priority: 5, bitIndex: 4 },
  { id: "google-and-ai-mechanism", role: "middle", subject: "Is AI search just hype?", preview: "Google and AI tools check many of the same trust signals.", body: "Hi {{first_name}}, it's {{sender_name}}.\n\nA fair question is, \"Is AI search really different, or is this just marketing hype?\"\n\nAI search isn't a separate universe from Google. When someone asks ChatGPT, an AI Overview, or another assistant which local business to trust, the system looks for information it can confirm across your website, business profiles, directories, reviews, and other sources.\n\nIf those sources disagree, omit an important service, or make the business look inactive, the system has less reason to recommend it.\n\nThis isn't about stuffing \"AI\" phrases into your website. It's about making accurate information about your business easy to find and verify.\n\nWe'll look at where that evidence is strong and where it gets thin for your market.\n\nIf AI search still sounds fuzzy or overhyped, reply with your question. I'll give you a straight answer.\n\nTalk soon,\n\nSanti", priority: 6, bitIndex: 5 },
  { id: "no-ad-spend-or-shared-leads", role: "middle", subject: "Does this require more ad spend?", preview: "The goal is to help buyers find and contact you directly.", body: "Hi {{first_name}}, it's {{sender_name}}.\n\nYou may be wondering whether getting more calls means buying more ads.\n\nIt doesn't.\n\nThe work is designed to help your business appear when people search and compare options through Google and AI tools. When someone finds you there, they contact your business directly. We aren't buying an inquiry and sending it to you alongside several competitors.\n\nThat doesn't mean you should stop running ads that already produce good customers. This gives you another way to be found without paying for every visit.\n\nWe'll compare this with the channels already producing calls for you when we talk.\n\nIf you have questions about how this differs from paid ads or shared leads, reply and ask.\n\nTalk soon,\n\nSanti", priority: 7, bitIndex: 6 },
  { id: "owner-time", role: "middle", subject: "How much time will this take from your team?", preview: "About 30 minutes during onboarding, then roughly 30 minutes per month.", body: "Hi {{first_name}}, it's {{sender_name}}.\n\nA concern I hear from busy owners is, \"Will this turn into another job for me or my team?\"\n\nPlan on about 30 minutes during onboarding, then roughly 30 minutes each month to review results and agree on priorities. We handle the implementation between those conversations.\n\nSomeone on your side may need to approve access or confirm business information. We won't hand you a weekly marketing checklist and call it a managed service.\n\nYou don't need to do anything before our call. Just know who could approve access to the website, Google Business Profile, and call reporting if you decide to move ahead.\n\nQuestions about what we'd need from your team? Reply and I'll walk you through it.\n\nTalk soon,\n\nSanti", priority: 8, bitIndex: 7 },
  { id: "rebuild-risk", role: "middle", subject: "You probably don't need to rebuild everything", preview: "I'll assess what already works before recommending a major change.", body: "Hi {{first_name}}, it's {{sender_name}}.\n\nA concern I hear is, \"Will we need to replace our website, CRM, or current marketing setup?\"\n\nProbably not.\n\nI start by looking at what already exists. Useful parts stay. We focus on the gaps most likely to hurt visibility and calls.\n\nSometimes the website needs structural work because the services or markets aren't clear. Other times, the larger problem sits outside the website in profiles, citations, reviews, or conflicting business information.\n\nThe inspection comes before any recommendation to rebuild something.\n\nIf a website or CRM change is already underway, we'll account for it when we talk.\n\nIf you're worried about protecting something in your current setup, reply with the question and I'll address it.\n\nTalk soon,\n\nSanti", priority: 9, bitIndex: 8 },
  { id: "proof-wesley-glen", role: "middle", subject: "Wesley Glen went from unranked to #2", preview: "The change happened in two weeks after the missing signals were identified.", body: "Hi {{first_name}}, it's {{sender_name}}.\n\nA question I hear is, \"How quickly could this produce a meaningful change?\"\n\nWesley Glen Retirement Community went from unranked to #2 across Google Maps and AI visibility in two weeks.\n\nI won't tell you every business reaches #2 in two weeks. The starting position, competition, location, reviews, and missing information all affect the result.\n\nWhat the result shows is that some visibility gaps can move quickly once we know exactly what's missing. The first step is finding out whether your business has that kind of problem.\n\nHave the service and market where you feel least visible in mind. We'll start there when we speak on {{meeting_local_weekday}}.\n\nIf you're wondering what's realistic for your timeline, reply and ask. I won't give you a canned promise.\n\nTalk soon,\n\nSanti", priority: 10, bitIndex: 9 },
  { id: "market-applicability", role: "middle", subject: "Will this work in your market?", preview: "That depends on your local demand, competition, and current visibility.", body: "Hi {{first_name}}, it's {{sender_name}}.\n\nA question I hear is, \"Will this work for a business like mine, in my market?\"\n\nThe honest answer starts with inspecting that market.\n\nPeople search, compare what they find, and decide which business feels credible enough to call. That behavior is common across service industries. The details change by service and location, which is why a generic campaign doesn't tell us much.\n\nPulpSense is rated 4.9 out of 5 by more than 500 service business owners. We've worked across different markets, but that experience doesn't remove the need to assess yours on its own facts.\n\nWe'll keep the conversation focused on the service category and geography that matter most to you.\n\nIf you're unsure whether this applies to your market, reply with the question. I'll answer based on what we can actually see.\n\nTalk soon,\n\nSanti", priority: 11, bitIndex: 10 },
  { id: "call-quality", role: "middle", subject: "What makes an inbound call worth having?", preview: "More calls only help when they come from people you can serve.", body: "Hi {{first_name}}, it's {{sender_name}}.\n\nA fair concern is, \"What if more calls just means more bad leads?\"\n\nA higher call count can look good while bringing inquiries for the wrong service, outside your area, or from people your business can't help. That isn't a useful result.\n\nWe'll look at the services and search intent worth prioritizing so the visibility work points toward demand you actually want.\n\nWhat happens after the phone rings is a separate part of the business, and I won't pretend marketing controls all of it. But we can make sure the work isn't aimed at searches you never wanted in the first place.\n\nWe'll define what a good inbound call looks like for your business on the call.\n\nIf call quality is your main concern, reply with any question you want me to address beforehand.\n\nTalk soon,\n\nSanti", priority: 12, bitIndex: 11 },
  { id: "economics", role: "middle", subject: "Let's check the economics before doing anything", preview: "Rough customer value and close-rate estimates are enough to test the math.", body: "Hi {{first_name}}, it's {{sender_name}}.\n\nA sensible question is, \"How do I know the likely return justifies the cost?\"\n\nWe can test that with rough numbers.\n\nWe need an estimate of what a typical new customer is worth, how often a qualified call turns into business, and how many additional calls would cover the investment.\n\nThe numbers don't need to be polished. A sensible range will tell us whether the opportunity looks healthy or whether it depends on an unrealistic close rate.\n\nHave your best estimates for customer value and close rate handy. We'll do the math openly instead of burying it in a marketing report.\n\nIf you want to pressure-test the economics before we speak, reply with your question.\n\nTalk soon,\n\nSanti", priority: 13, bitIndex: 12 },
  { id: "multiple-locations", role: "middle", subject: "Each location needs its own visibility plan", preview: "One strong market can hide a much weaker location.", body: "Hi {{first_name}}, it's {{sender_name}}.\n\nIf your business has several locations or service areas, you may be wondering whether one campaign can cover all of them.\n\nEach location faces different competitors and has its own business profile, reviews, local pages, and call demand. A single combined report can make the whole account look healthy while one important market barely appears.\n\nThe work can cover multiple locations, but the scope should reflect where the opportunity is. We may find that one market deserves attention first rather than trying to change every location at once.\n\nThink about which location has the largest gap between its business potential and current inbound calls. We can start there when we talk.\n\nIf your location setup makes this more complicated, reply with the question and I'll account for it.\n\nTalk soon,\n\nSanti", priority: 14, bitIndex: 13 },
  { id: "market-exclusivity", role: "middle", subject: "Will we work with one of your competitors?", preview: "We work with one business per service category in each market.", body: "Hi {{first_name}}, it's {{sender_name}}.\n\nA question that sometimes comes up is, \"Will you provide the same strategy to one of my direct competitors?\"\n\nNo. We work with one business per service category in each market.\n\nIt wouldn't make sense for us to build the same visibility advantage for two companies competing for the same local demand.\n\nThe category and geography need to be specific. A broad label like \"regional services\" doesn't tell either side what is protected.\n\nBefore the call, think about the exact service category and market you would want us to reserve. We'll confirm whether that scope is available before discussing a proposal.\n\nIf the exclusivity policy raises any questions, reply and ask me directly.\n\nTalk soon,\n\nSanti", priority: 15, bitIndex: 14 },
  { id: "why-now", role: "middle", subject: "Can buyers find you without searching your name?", preview: "A branded search doesn't show whether you're reaching new demand.", body: "Hi {{first_name}}, it's {{sender_name}}.\n\nA question worth asking is, \"Why should I deal with this now?\"\n\nSearching your company name only tells you whether people who already know you can find you. New buyers search for the service, the problem, and the location. They ask Google, Maps, AI Overviews, or ChatGPT which business to trust.\n\nIf your company is absent from those results, active demand is already going somewhere else.\n\nBefore our call, try one search without using your business name. Note which companies appear and why those results might look credible.\n\nOne search isn't a complete audit. It gives us a useful place to begin when we compare your market with what I found.\n\nIf anything about the search results confuses you, reply with the question and we'll sort it out.\n\nTalk soon,\n\nSanti", priority: 16, bitIndex: 15 },
  { id: "final-preparation", role: "final", subject: "A few things to have handy for our call", preview: "Rough estimates are enough. No deck or polished report needed.", body: "Hi {{first_name}}, it's {{sender_name}}.\n\nWe're speaking today at {{meeting_local_time}} {{attendee_timezone}}.\n\nYou don't need a deck or polished report for the meeting.\n\nHave a rough estimate of your typical monthly inbound calls and what a new customer, patient, case, or project is worth. It also helps to know which service and market you most want to grow.\n\nWe'll use that information to look at the visibility gap, check whether the economics make sense, and decide what I would prioritize first.\n\nIf I don't think there's a fit, I'll tell you. If there is, you'll leave knowing what the first priorities would be and how we'd measure the 45-call target.\n\nI'll speak with you at {{meeting_local_time}}.\n\nIf anything about the call or what to have ready is unclear, reply and ask.\n\nTalk soon,\n\nSanti" },
] as const satisfies readonly PrecallCopyModule[];

export const precallCopyById = Object.fromEntries(
  precallCopy.map((module) => [module.id, module]),
) as Record<PrecallModuleId, PrecallCopyModule>;

export const requiredPrecallVariables = [
  "first_name", "meeting_local_date", "meeting_local_time",
  "meeting_local_weekday", "attendee_timezone", "acquisition_source_label",
  "precall_opt_out_url", "business_postal_address", "sender_name",
] as const;
