export type Country = { flag: string; name: string; code: string; minDigits: number; maxDigits: number };

/** All countries sorted alphabetically by name. US pinned first as default. */
const COUNTRIES: Country[] = [
  { flag: '🇺🇸', name: 'United States', code: '+1', minDigits: 10, maxDigits: 10 },
  { flag: '🇦🇫', name: 'Afghanistan', code: '+93', minDigits: 9, maxDigits: 9 },
  { flag: '🇦🇱', name: 'Albania', code: '+355', minDigits: 9, maxDigits: 9 },
  { flag: '🇩🇿', name: 'Algeria', code: '+213', minDigits: 9, maxDigits: 9 },
  { flag: '🇦🇩', name: 'Andorra', code: '+376', minDigits: 6, maxDigits: 9 },
  { flag: '🇦🇴', name: 'Angola', code: '+244', minDigits: 9, maxDigits: 9 },
  { flag: '🇦🇬', name: 'Antigua and Barbuda', code: '+1268', minDigits: 7, maxDigits: 7 },
  { flag: '🇦🇷', name: 'Argentina', code: '+54', minDigits: 10, maxDigits: 10 },
  { flag: '🇦🇲', name: 'Armenia', code: '+374', minDigits: 8, maxDigits: 8 },
  { flag: '🇦🇺', name: 'Australia', code: '+61', minDigits: 9, maxDigits: 9 },
  { flag: '🇦🇹', name: 'Austria', code: '+43', minDigits: 10, maxDigits: 11 },
  { flag: '🇦🇿', name: 'Azerbaijan', code: '+994', minDigits: 9, maxDigits: 9 },
  { flag: '🇧🇸', name: 'Bahamas', code: '+1242', minDigits: 7, maxDigits: 7 },
  { flag: '🇧🇭', name: 'Bahrain', code: '+973', minDigits: 8, maxDigits: 8 },
  { flag: '🇧🇩', name: 'Bangladesh', code: '+880', minDigits: 10, maxDigits: 10 },
  { flag: '🇧🇧', name: 'Barbados', code: '+1246', minDigits: 7, maxDigits: 7 },
  { flag: '🇧🇾', name: 'Belarus', code: '+375', minDigits: 10, maxDigits: 10 },
  { flag: '🇧🇪', name: 'Belgium', code: '+32', minDigits: 9, maxDigits: 9 },
  { flag: '🇧🇿', name: 'Belize', code: '+501', minDigits: 7, maxDigits: 7 },
  { flag: '🇧🇯', name: 'Benin', code: '+229', minDigits: 8, maxDigits: 8 },
  { flag: '🇧🇹', name: 'Bhutan', code: '+975', minDigits: 8, maxDigits: 8 },
  { flag: '🇧🇴', name: 'Bolivia', code: '+591', minDigits: 8, maxDigits: 8 },
  { flag: '🇧🇦', name: 'Bosnia and Herzegovina', code: '+387', minDigits: 8, maxDigits: 8 },
  { flag: '🇧🇼', name: 'Botswana', code: '+267', minDigits: 7, maxDigits: 8 },
  { flag: '🇧🇷', name: 'Brazil', code: '+55', minDigits: 10, maxDigits: 11 },
  { flag: '🇧🇳', name: 'Brunei', code: '+673', minDigits: 7, maxDigits: 7 },
  { flag: '🇧🇬', name: 'Bulgaria', code: '+359', minDigits: 9, maxDigits: 9 },
  { flag: '🇧🇫', name: 'Burkina Faso', code: '+226', minDigits: 8, maxDigits: 8 },
  { flag: '🇧🇮', name: 'Burundi', code: '+257', minDigits: 8, maxDigits: 8 },
  { flag: '🇰🇭', name: 'Cambodia', code: '+855', minDigits: 8, maxDigits: 9 },
  { flag: '🇨🇲', name: 'Cameroon', code: '+237', minDigits: 9, maxDigits: 9 },
  { flag: '🇨🇦', name: 'Canada', code: '+1', minDigits: 10, maxDigits: 10 },
  { flag: '🇨🇻', name: 'Cape Verde', code: '+238', minDigits: 7, maxDigits: 7 },
  { flag: '🇨🇫', name: 'Central African Republic', code: '+236', minDigits: 8, maxDigits: 8 },
  { flag: '🇹🇩', name: 'Chad', code: '+235', minDigits: 8, maxDigits: 8 },
  { flag: '🇨🇱', name: 'Chile', code: '+56', minDigits: 9, maxDigits: 9 },
  { flag: '🇨🇳', name: 'China', code: '+86', minDigits: 11, maxDigits: 11 },
  { flag: '🇨🇴', name: 'Colombia', code: '+57', minDigits: 10, maxDigits: 10 },
  { flag: '🇰🇲', name: 'Comoros', code: '+269', minDigits: 7, maxDigits: 7 },
  { flag: '🇨🇬', name: 'Congo', code: '+242', minDigits: 9, maxDigits: 9 },
  { flag: '🇨🇩', name: 'Congo (DRC)', code: '+243', minDigits: 9, maxDigits: 9 },
  { flag: '🇨🇷', name: 'Costa Rica', code: '+506', minDigits: 8, maxDigits: 8 },
  { flag: '🇭🇷', name: 'Croatia', code: '+385', minDigits: 9, maxDigits: 9 },
  { flag: '🇨🇺', name: 'Cuba', code: '+53', minDigits: 8, maxDigits: 8 },
  { flag: '🇨🇾', name: 'Cyprus', code: '+357', minDigits: 8, maxDigits: 8 },
  { flag: '🇨🇿', name: 'Czech Republic', code: '+420', minDigits: 9, maxDigits: 9 },
  { flag: '🇩🇰', name: 'Denmark', code: '+45', minDigits: 8, maxDigits: 8 },
  { flag: '🇩🇯', name: 'Djibouti', code: '+253', minDigits: 8, maxDigits: 8 },
  { flag: '🇩🇲', name: 'Dominica', code: '+1767', minDigits: 7, maxDigits: 7 },
  { flag: '🇩🇴', name: 'Dominican Republic', code: '+1809', minDigits: 7, maxDigits: 7 },
  { flag: '🇪🇨', name: 'Ecuador', code: '+593', minDigits: 9, maxDigits: 9 },
  { flag: '🇪🇬', name: 'Egypt', code: '+20', minDigits: 10, maxDigits: 10 },
  { flag: '🇸🇻', name: 'El Salvador', code: '+503', minDigits: 8, maxDigits: 8 },
  { flag: '🇬🇶', name: 'Equatorial Guinea', code: '+240', minDigits: 9, maxDigits: 9 },
  { flag: '🇪🇷', name: 'Eritrea', code: '+291', minDigits: 7, maxDigits: 7 },
  { flag: '🇪🇪', name: 'Estonia', code: '+372', minDigits: 7, maxDigits: 8 },
  { flag: '🇸🇿', name: 'Eswatini', code: '+268', minDigits: 8, maxDigits: 8 },
  { flag: '🇪🇹', name: 'Ethiopia', code: '+251', minDigits: 9, maxDigits: 9 },
  { flag: '🇫🇯', name: 'Fiji', code: '+679', minDigits: 7, maxDigits: 7 },
  { flag: '🇫🇮', name: 'Finland', code: '+358', minDigits: 9, maxDigits: 10 },
  { flag: '🇫🇷', name: 'France', code: '+33', minDigits: 9, maxDigits: 9 },
  { flag: '🇬🇦', name: 'Gabon', code: '+241', minDigits: 7, maxDigits: 8 },
  { flag: '🇬🇲', name: 'Gambia', code: '+220', minDigits: 7, maxDigits: 7 },
  { flag: '🇬🇪', name: 'Georgia', code: '+995', minDigits: 9, maxDigits: 9 },
  { flag: '🇩🇪', name: 'Germany', code: '+49', minDigits: 10, maxDigits: 11 },
  { flag: '🇬🇭', name: 'Ghana', code: '+233', minDigits: 9, maxDigits: 9 },
  { flag: '🇬🇷', name: 'Greece', code: '+30', minDigits: 10, maxDigits: 10 },
  { flag: '🇬🇩', name: 'Grenada', code: '+1473', minDigits: 7, maxDigits: 7 },
  { flag: '🇬🇹', name: 'Guatemala', code: '+502', minDigits: 8, maxDigits: 8 },
  { flag: '🇬🇳', name: 'Guinea', code: '+224', minDigits: 9, maxDigits: 9 },
  { flag: '🇬🇼', name: 'Guinea-Bissau', code: '+245', minDigits: 7, maxDigits: 7 },
  { flag: '🇬🇾', name: 'Guyana', code: '+592', minDigits: 7, maxDigits: 7 },
  { flag: '🇭🇹', name: 'Haiti', code: '+509', minDigits: 8, maxDigits: 8 },
  { flag: '🇭🇳', name: 'Honduras', code: '+504', minDigits: 8, maxDigits: 8 },
  { flag: '🇭🇰', name: 'Hong Kong', code: '+852', minDigits: 8, maxDigits: 8 },
  { flag: '🇭🇺', name: 'Hungary', code: '+36', minDigits: 9, maxDigits: 9 },
  { flag: '🇮🇸', name: 'Iceland', code: '+354', minDigits: 7, maxDigits: 7 },
  { flag: '🇮🇳', name: 'India', code: '+91', minDigits: 10, maxDigits: 10 },
  { flag: '🇮🇩', name: 'Indonesia', code: '+62', minDigits: 10, maxDigits: 12 },
  { flag: '🇮🇷', name: 'Iran', code: '+98', minDigits: 10, maxDigits: 10 },
  { flag: '🇮🇶', name: 'Iraq', code: '+964', minDigits: 10, maxDigits: 10 },
  { flag: '🇮🇪', name: 'Ireland', code: '+353', minDigits: 9, maxDigits: 9 },
  { flag: '🇮🇱', name: 'Israel', code: '+972', minDigits: 9, maxDigits: 9 },
  { flag: '🇮🇹', name: 'Italy', code: '+39', minDigits: 9, maxDigits: 10 },
  { flag: '🇨🇮', name: 'Ivory Coast', code: '+225', minDigits: 10, maxDigits: 10 },
  { flag: '🇯🇲', name: 'Jamaica', code: '+1876', minDigits: 7, maxDigits: 7 },
  { flag: '🇯🇵', name: 'Japan', code: '+81', minDigits: 10, maxDigits: 10 },
  { flag: '🇯🇴', name: 'Jordan', code: '+962', minDigits: 9, maxDigits: 9 },
  { flag: '🇰🇿', name: 'Kazakhstan', code: '+7', minDigits: 10, maxDigits: 10 },
  { flag: '🇰🇪', name: 'Kenya', code: '+254', minDigits: 9, maxDigits: 9 },
  { flag: '🇰🇮', name: 'Kiribati', code: '+686', minDigits: 5, maxDigits: 8 },
  { flag: '🇰🇼', name: 'Kuwait', code: '+965', minDigits: 8, maxDigits: 8 },
  { flag: '🇰🇬', name: 'Kyrgyzstan', code: '+996', minDigits: 9, maxDigits: 9 },
  { flag: '🇱🇦', name: 'Laos', code: '+856', minDigits: 8, maxDigits: 10 },
  { flag: '🇱🇻', name: 'Latvia', code: '+371', minDigits: 8, maxDigits: 8 },
  { flag: '🇱🇧', name: 'Lebanon', code: '+961', minDigits: 7, maxDigits: 8 },
  { flag: '🇱🇸', name: 'Lesotho', code: '+266', minDigits: 8, maxDigits: 8 },
  { flag: '🇱🇷', name: 'Liberia', code: '+231', minDigits: 7, maxDigits: 9 },
  { flag: '🇱🇾', name: 'Libya', code: '+218', minDigits: 9, maxDigits: 9 },
  { flag: '🇱🇮', name: 'Liechtenstein', code: '+423', minDigits: 7, maxDigits: 7 },
  { flag: '🇱🇹', name: 'Lithuania', code: '+370', minDigits: 8, maxDigits: 8 },
  { flag: '🇱🇺', name: 'Luxembourg', code: '+352', minDigits: 9, maxDigits: 9 },
  { flag: '🇲🇴', name: 'Macau', code: '+853', minDigits: 8, maxDigits: 8 },
  { flag: '🇲🇬', name: 'Madagascar', code: '+261', minDigits: 9, maxDigits: 9 },
  { flag: '🇲🇼', name: 'Malawi', code: '+265', minDigits: 9, maxDigits: 9 },
  { flag: '🇲🇾', name: 'Malaysia', code: '+60', minDigits: 9, maxDigits: 10 },
  { flag: '🇲🇻', name: 'Maldives', code: '+960', minDigits: 7, maxDigits: 7 },
  { flag: '🇲🇱', name: 'Mali', code: '+223', minDigits: 8, maxDigits: 8 },
  { flag: '🇲🇹', name: 'Malta', code: '+356', minDigits: 8, maxDigits: 8 },
  { flag: '🇲🇷', name: 'Mauritania', code: '+222', minDigits: 8, maxDigits: 8 },
  { flag: '🇲🇺', name: 'Mauritius', code: '+230', minDigits: 8, maxDigits: 8 },
  { flag: '🇲🇽', name: 'Mexico', code: '+52', minDigits: 10, maxDigits: 10 },
  { flag: '🇲🇩', name: 'Moldova', code: '+373', minDigits: 8, maxDigits: 8 },
  { flag: '🇲🇨', name: 'Monaco', code: '+377', minDigits: 8, maxDigits: 8 },
  { flag: '🇲🇳', name: 'Mongolia', code: '+976', minDigits: 8, maxDigits: 8 },
  { flag: '🇲🇪', name: 'Montenegro', code: '+382', minDigits: 8, maxDigits: 8 },
  { flag: '🇲🇦', name: 'Morocco', code: '+212', minDigits: 9, maxDigits: 9 },
  { flag: '🇲🇿', name: 'Mozambique', code: '+258', minDigits: 9, maxDigits: 9 },
  { flag: '🇲🇲', name: 'Myanmar', code: '+95', minDigits: 8, maxDigits: 10 },
  { flag: '🇳🇦', name: 'Namibia', code: '+264', minDigits: 9, maxDigits: 9 },
  { flag: '🇳🇵', name: 'Nepal', code: '+977', minDigits: 10, maxDigits: 10 },
  { flag: '🇳🇱', name: 'Netherlands', code: '+31', minDigits: 9, maxDigits: 9 },
  { flag: '🇳🇿', name: 'New Zealand', code: '+64', minDigits: 8, maxDigits: 9 },
  { flag: '🇳🇮', name: 'Nicaragua', code: '+505', minDigits: 8, maxDigits: 8 },
  { flag: '🇳🇪', name: 'Niger', code: '+227', minDigits: 8, maxDigits: 8 },
  { flag: '🇳🇬', name: 'Nigeria', code: '+234', minDigits: 10, maxDigits: 10 },
  { flag: '🇰🇵', name: 'North Korea', code: '+850', minDigits: 8, maxDigits: 10 },
  { flag: '🇲🇰', name: 'North Macedonia', code: '+389', minDigits: 8, maxDigits: 8 },
  { flag: '🇳🇴', name: 'Norway', code: '+47', minDigits: 8, maxDigits: 8 },
  { flag: '🇴🇲', name: 'Oman', code: '+968', minDigits: 8, maxDigits: 8 },
  { flag: '🇵🇰', name: 'Pakistan', code: '+92', minDigits: 10, maxDigits: 10 },
  { flag: '🇵🇸', name: 'Palestine', code: '+970', minDigits: 9, maxDigits: 9 },
  { flag: '🇵🇦', name: 'Panama', code: '+507', minDigits: 8, maxDigits: 8 },
  { flag: '🇵🇬', name: 'Papua New Guinea', code: '+675', minDigits: 8, maxDigits: 8 },
  { flag: '🇵🇾', name: 'Paraguay', code: '+595', minDigits: 9, maxDigits: 9 },
  { flag: '🇵🇪', name: 'Peru', code: '+51', minDigits: 9, maxDigits: 9 },
  { flag: '🇵🇭', name: 'Philippines', code: '+63', minDigits: 10, maxDigits: 10 },
  { flag: '🇵🇱', name: 'Poland', code: '+48', minDigits: 9, maxDigits: 9 },
  { flag: '🇵🇹', name: 'Portugal', code: '+351', minDigits: 9, maxDigits: 9 },
  { flag: '🇵🇷', name: 'Puerto Rico', code: '+1787', minDigits: 7, maxDigits: 7 },
  { flag: '🇶🇦', name: 'Qatar', code: '+974', minDigits: 8, maxDigits: 8 },
  { flag: '🇷🇴', name: 'Romania', code: '+40', minDigits: 9, maxDigits: 9 },
  { flag: '🇷🇺', name: 'Russia', code: '+7', minDigits: 10, maxDigits: 10 },
  { flag: '🇷🇼', name: 'Rwanda', code: '+250', minDigits: 9, maxDigits: 9 },
  { flag: '🇰🇳', name: 'Saint Kitts and Nevis', code: '+1869', minDigits: 7, maxDigits: 7 },
  { flag: '🇱🇨', name: 'Saint Lucia', code: '+1758', minDigits: 7, maxDigits: 7 },
  { flag: '🇻🇨', name: 'Saint Vincent', code: '+1784', minDigits: 7, maxDigits: 7 },
  { flag: '🇼🇸', name: 'Samoa', code: '+685', minDigits: 5, maxDigits: 7 },
  { flag: '🇸🇦', name: 'Saudi Arabia', code: '+966', minDigits: 9, maxDigits: 9 },
  { flag: '🇸🇳', name: 'Senegal', code: '+221', minDigits: 9, maxDigits: 9 },
  { flag: '🇷🇸', name: 'Serbia', code: '+381', minDigits: 9, maxDigits: 9 },
  { flag: '🇸🇨', name: 'Seychelles', code: '+248', minDigits: 7, maxDigits: 7 },
  { flag: '🇸🇱', name: 'Sierra Leone', code: '+232', minDigits: 8, maxDigits: 8 },
  { flag: '🇸🇬', name: 'Singapore', code: '+65', minDigits: 8, maxDigits: 8 },
  { flag: '🇸🇰', name: 'Slovakia', code: '+421', minDigits: 9, maxDigits: 9 },
  { flag: '🇸🇮', name: 'Slovenia', code: '+386', minDigits: 8, maxDigits: 8 },
  { flag: '🇸🇴', name: 'Somalia', code: '+252', minDigits: 8, maxDigits: 8 },
  { flag: '🇿🇦', name: 'South Africa', code: '+27', minDigits: 9, maxDigits: 9 },
  { flag: '🇰🇷', name: 'South Korea', code: '+82', minDigits: 10, maxDigits: 10 },
  { flag: '🇸🇸', name: 'South Sudan', code: '+211', minDigits: 9, maxDigits: 9 },
  { flag: '🇪🇸', name: 'Spain', code: '+34', minDigits: 9, maxDigits: 9 },
  { flag: '🇱🇰', name: 'Sri Lanka', code: '+94', minDigits: 9, maxDigits: 9 },
  { flag: '🇸🇩', name: 'Sudan', code: '+249', minDigits: 9, maxDigits: 9 },
  { flag: '🇸🇷', name: 'Suriname', code: '+597', minDigits: 7, maxDigits: 7 },
  { flag: '🇸🇪', name: 'Sweden', code: '+46', minDigits: 9, maxDigits: 9 },
  { flag: '🇨🇭', name: 'Switzerland', code: '+41', minDigits: 9, maxDigits: 9 },
  { flag: '🇸🇾', name: 'Syria', code: '+963', minDigits: 9, maxDigits: 9 },
  { flag: '🇹🇼', name: 'Taiwan', code: '+886', minDigits: 9, maxDigits: 9 },
  { flag: '🇹🇯', name: 'Tajikistan', code: '+992', minDigits: 9, maxDigits: 9 },
  { flag: '🇹🇿', name: 'Tanzania', code: '+255', minDigits: 9, maxDigits: 9 },
  { flag: '🇹🇭', name: 'Thailand', code: '+66', minDigits: 9, maxDigits: 9 },
  { flag: '🇹🇱', name: 'Timor-Leste', code: '+670', minDigits: 7, maxDigits: 8 },
  { flag: '🇹🇬', name: 'Togo', code: '+228', minDigits: 8, maxDigits: 8 },
  { flag: '🇹🇴', name: 'Tonga', code: '+676', minDigits: 5, maxDigits: 7 },
  { flag: '🇹🇹', name: 'Trinidad and Tobago', code: '+1868', minDigits: 7, maxDigits: 7 },
  { flag: '🇹🇳', name: 'Tunisia', code: '+216', minDigits: 8, maxDigits: 8 },
  { flag: '🇹🇷', name: 'Turkey', code: '+90', minDigits: 10, maxDigits: 10 },
  { flag: '🇹🇲', name: 'Turkmenistan', code: '+993', minDigits: 8, maxDigits: 8 },
  { flag: '🇺🇬', name: 'Uganda', code: '+256', minDigits: 9, maxDigits: 9 },
  { flag: '🇺🇦', name: 'Ukraine', code: '+380', minDigits: 9, maxDigits: 9 },
  { flag: '🇦🇪', name: 'United Arab Emirates', code: '+971', minDigits: 9, maxDigits: 9 },
  { flag: '🇬🇧', name: 'United Kingdom', code: '+44', minDigits: 10, maxDigits: 10 },
  { flag: '🇺🇾', name: 'Uruguay', code: '+598', minDigits: 8, maxDigits: 8 },
  { flag: '🇺🇿', name: 'Uzbekistan', code: '+998', minDigits: 9, maxDigits: 9 },
  { flag: '🇻🇺', name: 'Vanuatu', code: '+678', minDigits: 5, maxDigits: 7 },
  { flag: '🇻🇪', name: 'Venezuela', code: '+58', minDigits: 10, maxDigits: 10 },
  { flag: '🇻🇳', name: 'Vietnam', code: '+84', minDigits: 9, maxDigits: 10 },
  { flag: '🇾🇪', name: 'Yemen', code: '+967', minDigits: 9, maxDigits: 9 },
  { flag: '🇿🇲', name: 'Zambia', code: '+260', minDigits: 9, maxDigits: 9 },
  { flag: '🇿🇼', name: 'Zimbabwe', code: '+263', minDigits: 9, maxDigits: 9 },
];

export { COUNTRIES };
